Add GitHub Actions workflow for building Windows executable

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -14,25 +14,34 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-
       - name: Set up JDK 20
         uses: actions/setup-java@v3
         with:
           java-version: '20'
-          distribution: 'temurin'  #
+          distribution: 'temurin'
 
+      - name: Set up Maven
+        uses: actions/setup-java@v3
+        with:
+          java-version: '20'
+          distribution: 'temurin'
+          cache: maven
 
       - name: Build with Maven
         run: mvn clean package
 
+      - name: Verify Build Output
+        run: |
+          if not exist target/tareas-0.0.1-SNAPSHOT.jar (
+            echo "Error: JAR file not found!" && exit 1
+          )
 
       - name: Create Windows Executable
         run: |
           jpackage --input target/ --name Tareas --main-jar tareas-0.0.1-SNAPSHOT.jar --main-class gm.tareas.TareasApplication --type app-image --dest output
 
-
       - name: Upload Executable
         uses: actions/upload-artifact@v3
         with:
-          name: Tareas
+          name: Tareas-Windows
           path: output/
